language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
addons:
  apt:
    packages:
     - libzbar-dev

install: pip install tox-travis pytest-travis-fold
script: tox
